### PR TITLE
Fixes for Docker containers on Linux

### LINKED ISSUE #1: Can't start the p4 shell in Linux environment.
The hostname `host.docker.internal` only works if you're using `docker for mac`. it won't be resolved to any valid address in Linux system.
```
CRITICAL:root:StreamChannel error, closing stream
CRITICAL:root:P4Runtime RPC error (UNAVAILABLE): DNS resolution failed
CRITICAL:root:Failed to establish session with server
```

Ref:
https://docs.docker.com/docker-for-mac/networking/

### LINKED ISSUE #2: Run ./p4rt-shell.sh ,but failed with  CRITICAL error
I follow the basic guides . Now  I can run **start-mn.sh**  successfully.
image

But , run **p4rt-shell.sh** failed :
image

I try this on Ubuntu16.04 and CentOS 7 and  both get the same error

### PR DESCRIPTION
**Pull request by bocon13**
Fixing host.docker.internal
- For p4rt-shell and gnmi-cli, use host networking
- For onos, use container that has patch /etc/hosts

fixes #1 
fixes #2

### CODE REVIEW

**Comment by bocon13** [comment]
@hwchiu here's an alternative approach

**Review by hwchiu — COMMENTED** [review]
LGTM

**Review by Yi-Tseng — APPROVED** [review]
lgtm

**Comment by hwchiu** [comment]
By the way, we use the `network=host` for those containers and it's possible for the port collision if there're existing mininet or ONOS program.
We should note this in the README to avoid those problems.

**Pull request merged**
